config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resource :pictures
  
  get '/preview/:id', to: 'pictures#preview'
  patch 'pictures/:id', to: 'pictures#update'
  get '/next_image/:id', to: 'pictures#next_image'
  get '/prev_image/:id', to: 'pictures#prev_image'
  get '/annotations/:id', to: 'pictures#annotations'
end

app/models/annotation.rb
class Annotation < ApplicationRecord
    belongs_to :picture
   
    validates_with AnnotationValidator
    
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end
class AnnotationValidator < ActiveModel::Validator
  def validate(annotation)
        if annotation.picture.annotations.count > 9
          annotation.errors.add :base, "You can only add 10 annotations"
        end
  end
end

app/models/picture.rb
class Picture < ApplicationRecord
    has_many :annotations, dependent: :destroy
    mount_uploader :picture, PictureUploader
    
    def next
      Picture.where("id > ?", id).first
    end
    
    def prev
      Picture.where("id < ?", id).last
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
    def new
        @picture = Picture.new
        @annotations = @picture.annotations
    end
    
    def edit 
        @picture = Picture.find(params[:format])
        
    end

    def preview
        # byebug
        @picture = Picture.find(params[:id])
        respond_to do |format|
            format.js { render partial: 'pictures/preview' }
        end
    end

    def show 
        @pictures  = Picture.paginate(:page => params[:page], :per_page=>6)
    end

    def destroy
        @picture = Picture.find(params[:format])
        @picture.destroy
        flash[:notice] = "Your image is successfully deleted"
        redirect_to @picture
    end

    def annotations
        @picture = Picture.find(params[:id])
        @annotations = @picture.annotations
        respond_to do |format|
            format.js { render partial: 'pictures/annotations' }
        end
    end

    def next_image
        # byebug
        @picture = Picture.find(params[:id])
        
        unless @picture.next 
            @picture = Picture.first 
        else
            @picture = @picture.next
        end
        
        respond_to do |format|
            format.js { render partial: 'pictures/next' }
        end
    end

    def prev_image
        # byebug
        @picture = Picture.find(params[:id])
        
        unless @picture.prev 
            @picture = Picture.last
        else
            @picture = @picture.prev
        end
        
        respond_to do |format|
            format.js { render partial: 'pictures/next' }
        end
    end

    def update
        # byebug
        @picture = Picture.find(params[:id])
        
        #annotation update
        index = 1
        while index < params[:picture][:key].length
            unless Annotation.find_by(key: "#{params[:picture][:key][index]}", value: "#{params[:picture][:value][index]}", picture_id: "#{params[:id]}")
                Annotation.create(key: "#{params[:picture][:key][index]}", value: "#{params[:picture][:value][index]}", picture_id: "#{params[:id]}") 
            end
            index = index + 1
        end
        @annotations = @picture.annotations
        @annotations.each{ |annotation|
            annotation.destroy unless params[:picture][:value].include?(annotation.value)
        }

        #picture update
        if params[:picture][:picture]
            @picture.picture = params[:picture][:picture] 
            @picture.save
        end
        flash[:notice] = "Image was successfully updated"
        redirect_to pictures_path
    end
    

    def create
        # byebug
        @picture = Picture.new(picture_params)
        if @picture.save
            keys = []
            values = []
            params.each{ |key,value|
                keys.push(value) if key.include? "key"
                values.push(value) if key.include? "value"
            }
            index = 0
            while index < keys.length 
                Annotation.create(key: keys[index], value: values[index],picture_id: @picture.id)
                index = index + 1
            end
            flash[:notice] = "Image was successfully added"
            redirect_to root_path 
        else
            flash.now[:alert] = "Please upload a valid image format"
            render :new 
        end
        
    end

    

    private
    def picture_params
        params.require(:picture).permit(:picture)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
        
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<% if notice %>
 	<div class='alert alert-success'>
         <button type="button" class="close" data-dismiss="alert" aria-label="Close">
             <span aria-hidden="true">&times;</span>
         </button>
 		<%= notice %>
 	</div>
 <% end %>

 <% if alert %>
 	<div class='alert alert-danger'>
         <button type="button" class="close" data-dismiss="alert" aria-label="Close">
             <span aria-hidden="true">&times;</span>
         </button>
 		<%= alert %>
 	</div>
 <% end %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImageAnnotation</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src=
        "https://code.jquery.com/jquery-3.5.1.min.js">
    </script>
  </head>

  <body>
    <div class="container">
       <%= render 'layouts/messages' %>
       <%= yield %>
     </div>
  </body>
</html>

app/views/pictures/_annotations.html.erb
<div class="container" style = "background-color: rgb(106, 227, 116)">

<h1>Annotations</h1>
<div class="close-btn2">
    ×
</div>


        
<div class="row">
  <div class="col-9">
        <%# <%= form_with(model: @picture, local: true)  :html => { multipart: true } do |f| %> 
        <%= form_with model: @picture, url: "/pictures/#{@picture.id}", method: :patch do |f| %>
            
          
            <div class="form-row" id="append-item1">
                <div class="form-row" id="removerow2">
                    <div class="form-group right-margin">
                        <%= f.label :key %>
                        <%= f.text_field :key, multiple: true%>
                    </div>
                    <div class="form-group right-margin">
                        <%= f.label :value %>
                        <%= f.text_field :value, multiple: true %>
                    </div>
                    <div class="form-group right-margin">
                        <%= f.button :Remove,id: "remove2", class: "btn btn-secondary"%>
                    </div>
                </div>
            </div>

            <%if @picture.annotations %>
                <div class="form-row" id="dynamic">
                    <% @picture.annotations.each do |i|%>
                            <div class="form-row" id="removerow1">
                            
                                <div class="form-group right-margin">
                                    <%= f.label :key %>
                                    <%= f.text_field :key, value: "#{i.key}", multiple: true%>
                                </div>
                                <div class="form-group right-margin">
                                    <%= f.label :value %>
                                    <%= f.text_field :value, value: "#{i.value}",multiple: true %>
                                </div>
                                <div class="form-group right-margin">
                                    <%= f.button :Remove,id: "remove1", class: "btn btn-secondary"%>
                                </div>
                            </div>
                    <% end %>
                </div>
                <div class="form-group right-margin">
                    <%= f.button :add, :type => 'button', class: "btn btn-success add"%> 
                </div>
            
                
            <% end %>  
            
            <%= f.submit 'upload', :class => "btn btn-success"%>
            <input id="amount" type = "number"  value = "<%=@picture.annotations.count%>"/>
        <% end %>
    </div>
</div>
    </div>    
                
        

app/views/pictures/_annotations.js.erb
document.querySelector('.content2').innerHTML= '<%= j render 'pictures/annotations.html' %>'
$(".content2").toggle();

$(".close-btn2").on("click", function(){  
            // $(this).closest('.content2').toggle();
            $(".content2").toggle();
        
          });


          
  // $(".close-btn1").on("click", function(){  
  //   // $(this).closest('.content1').toggle();
  //   $(".content1").toggle();

  // });

  $(".add").on("click", function(){     

    if(($("#amount").val()) < 10 ){
      var qty = parseInt($('#amount').val());
        
      $("#dynamic").append($("#append-item1").html());
            var new_qty = qty + 1;
            if (new_qty < 0) {
                    new_qty = 0;
            }
            $('#amount').val(new_qty);
    }  
  });
  
  $(document).on('click', '#remove1', function () {
    $(this).closest('#removerow1').remove();
    var qty = parseInt($('#amount').val());        
            var new_qty = qty - 1;
            if (new_qty < 0) {
                    new_qty = 0;
            }
            $('#amount').val(new_qty);
  });
  
  $(document).on('click', '#remove2', function () {
    $(this).closest('#removerow2').remove();
    var qty = parseInt($('#amount').val());        
            var new_qty = qty - 1;
            if (new_qty < 0) {
                    new_qty = 0;
            }
            $('#amount').val(new_qty)
  });

app/views/pictures/_next.js.erb
$(".content1").css('display','none');



document.querySelector('.content1').innerHTML= '<%= j render 'pictures/preview.html' %>'
$(".content1").toggle();

$(".close-btn1").on("click", function(){  
            // $(this).closest('.content1').toggle();
            $(".content1").toggle();
        
          }); 

app/views/pictures/_preview.html.erb
<div class="close-btn1">
    ×
</div>
<div>

    <div>
    <%# <%= link_to "/next_image/#{picture.id}", :remote => true do %>  
        <%= link_to "/prev_image/#{@picture.id}", :remote => true do %> 
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
        <% end %> 
        
    <%# <% end %> 

        <%= image_tag "#{@picture.picture}",size: "1000x600" %>
        <%= link_to "/next_image/#{@picture.id}", :remote => true do %> 
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
        <% end %> 
    </div>
</div>
<div>
    <%= link_to 'Annotate', "/annotations/#{@picture.id}",:remote => true,
                                                    class: 'btn btn btn-info' %>
    <%= link_to 'Edit', edit_pictures_path(@picture), method: :get,
                                                    class: 'btn btn btn-info' %>

    <%= link_to 'Remove', pictures_path(@picture), method: :delete, data: {confirm: 'Are you sure?'},
                                                    class: 'btn btn-sm btn-warning' %>
    
    

</div>

app/views/pictures/_preview.js.erb
document.querySelector('.content1').innerHTML= '<%= j render 'pictures/preview.html' %>'
$(".content1").toggle();

$(".close-btn1").on("click", function(){  
            // $(this).closest('.content1').toggle();
            $(".content1").toggle();
        
          });

app/views/pictures/edit.html.erb
<div class="container text-center upload-heading">
    <h1>Edit image</h1>
</div>



<div class="row">
  <div class="col-9">
        <%# <%= form_with(model: @picture, local: true)  :html => { multipart: true } do |f| %> 
        <%= form_with model: @picture, url: '/pictures', method: :patch,:html => { multipart: true } do |f| %>
            
            <%# <%= image_tag(@picture.picture_url) if @picture.picture? %> 
            <div class="form-row" id="append-item1">
                <div class="form-row" id="removerow2">
                    <div class="form-group right-margin">
                        <%= f.label :key %>
                        <%= f.text_field :key, multiple: true%>
                    </div>
                    <div class="form-group right-margin">
                        <%= f.label :value %>
                        <%= f.text_field :value, multiple: true %>
                    </div>
                    <div class="form-group right-margin">
                        <%= f.button :Remove,id: "remove2", class: "btn btn-secondary"%>
                    </div>
                </div>
            </div>
            <%= f.file_field :picture , accept: 'picture/jpeg,picture/jpg,picture/png', :class => "form-control form-control-lg"%>
           <%# <%= @uploader.retrieve_from_store!("#{@picture}")%> 
            <%if @picture.annotations %>
                <div class="form-row" id="dynamic">
                    <% @picture.annotations.each do |i|%>
                            <div class="form-row" id="removerow1">
                            
                                <div class="form-group right-margin">
                                    <%= f.label :key %>
                                    <%= f.text_field :key, value: "#{i.key}", multiple: true%>
                                </div>
                                <div class="form-group right-margin">
                                    <%= f.label :value %>
                                    <%= f.text_field :value, value: "#{i.value}",multiple: true %>
                                </div>
                                <div class="form-group right-margin">
                                    <%= f.button :Remove,id: "remove1", class: "btn btn-secondary"%>
                                </div>
                            </div>
                    <% end %>
                </div>
                <div class="form-group right-margin">
                    <%= f.button :add, :type => 'button', class: "btn btn-success add"%> 
                </div>
                <%# <%= f.number_field :amount, value: "#{@picture.annotations.count}" %>
                
            <% end %>  
            
            <%= f.submit 'upload', :class => "btn btn-success"%>
            <input id="amount" type = "number"  value = "<%=@picture.annotations.count%>"/>
        <% end %>
    </div>
</div>

app/views/pictures/new.html.erb
    <div class="container text-center upload-heading">
        <h1>Upload image</h1>
    </div>

    
<div class="container d-flex justify-content-center">
<div class="row">
<div class="col-mt-6  " >

    <%= form_for @picture, :html => { multipart: true } do |f| %>
        
            
            <%= f.file_field :picture, accept: 'picture/jpeg,picture/jpg,picture/png', :class => "form-control form-control-lg "%>
            

            <%# <form action="#" name = "annotation"> %>
            
                <div id="original-inputs" class = "my-6 my-6">
                    <div id = "inputFormRow">
                
                        <label class = "font-weight-bold">Key</label>
                        <input id="key" name="key" />
                        <label class = "font-weight-bold">Value</label>
                        <input id="value" name="value" />
                        <%# <button type='button' class="onclick">Add More</button> %>
                        <button type='button' id="removeRow" class="btn btn-secondary">Remove</button>
                        <br/>
                    </div>
                    
                </div>
            
                <input id="n" type = "number" value = 0 />
                
                 <%# <%= form.label :query, "Search for:" %>
                <div class="dynamic-inputs" name='annotation'></div> 
                <button type='button' id="onclick" class="onclick btn btn-secondary">Add Annotation</button>
                
            <%# </form> %>
        
        <%= f.submit 'upload', :class => "btn btn-success"%>
    
    <% end %>
</div>
</div>
</div>





    

app/views/pictures/show.html.erb
<div class="container text-center">
    <h1>Listing of Images</h1>
</div>  

<div class="container">
    <%= will_paginate @pictures, list_classes: %w(pagination justify-content-center)%> 
        <div class="row">
            <div class="col"> 
                <table class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Upload date</th>
                            <th scope="col">Image</th>
                            <th scope="col">Edit</th>
                            <th scope="col">Delete</th>
                        </tr>
                    </thead>
                    <tbody>
                
                        <% @pictures.each do |picture| %>
                            <tr>
                                <th scope="row" >
                                    <%= link_to "/preview/#{picture.id}", :remote => true do %>
                                    <%= picture.picture.identifier %>
                                    <% end %>
                                </th>
                                <td><%= picture.created_at.to_date %></td>
                                <td>
                                    <%# <%= link_to "/preview/#{picture.id}", :remote => true do %>
                                    <%= image_tag "#{picture.picture}", size: "100x70",class: "image-tag" %>
                                    <%# <% end %> 
                                </td> 
                                  
                                            
                                <td><%= link_to 'Edit', edit_pictures_path(picture), method: :get,
                                                    class: 'btn btn btn-info' %></td> 
                            <td><%= link_to 'Remove', pictures_path(picture), method: :delete, data: {confirm: 'Are you sure?'},
                                                    class: 'btn btn-sm btn-warning' %></td> 
                            </tr> 
                            <div class = "content1">
                            </div>
                        <% end %>   
                    </tbody>
                </table> 
                
            </div>
        </div>  
    <%= will_paginate @pictures, list_classes: %w(pagination justify-content-center)%> 
</div> 
<div class = "content2">
</div>


<script type="text/javascript">
        
    </script>

app/views/welcome/index.html.erb
<div class="container welcome">
    <div class="container text-center">
        <h1>Welcome to image annotation service</h1>
    </div>
    <div class="container welcome" >
        <div class="row text-center">
            <div class="col text-center" >
                <button type="button" class="btn btn-info btn-lg">
                    <%= link_to "View images", pictures_path, :class => "text-white text-decoration-none"%>
                </button>
            </div>
            <div class="col text-center">
                <button type="button" class="btn btn-info btn-lg">
                    <%= link_to "Upload Image", new_pictures_path, :class => "text-white text-decoration-none"%>
                </button>
            </div>
        </div>
    </div>
</div>